// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipv4_rib_edm_advert.proto

package cisco_ios_xr_ip_rib_ipv4_oper_rib_vrfs_vrf_afs_af_safs_saf_ip_rib_route_table_names_ip_rib_route_table_name_adverts_advert

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Route advertisement information
type Ipv4RibEdmAdvert_KEYS struct {
	VrfName              string   `protobuf:"bytes,1,opt,name=vrf_name,json=vrfName,proto3" json:"vrf_name,omitempty"`
	AfName               string   `protobuf:"bytes,2,opt,name=af_name,json=afName,proto3" json:"af_name,omitempty"`
	SafName              string   `protobuf:"bytes,3,opt,name=saf_name,json=safName,proto3" json:"saf_name,omitempty"`
	RouteTableName       string   `protobuf:"bytes,4,opt,name=route_table_name,json=routeTableName,proto3" json:"route_table_name,omitempty"`
	Address              string   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PrefixLength         uint32   `protobuf:"varint,6,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ipv4RibEdmAdvert_KEYS) Reset()         { *m = Ipv4RibEdmAdvert_KEYS{} }
func (m *Ipv4RibEdmAdvert_KEYS) String() string { return proto.CompactTextString(m) }
func (*Ipv4RibEdmAdvert_KEYS) ProtoMessage()    {}
func (*Ipv4RibEdmAdvert_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_ipv4_rib_edm_advert_0cad3ad845b7d984, []int{0}
}
func (m *Ipv4RibEdmAdvert_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ipv4RibEdmAdvert_KEYS.Unmarshal(m, b)
}
func (m *Ipv4RibEdmAdvert_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ipv4RibEdmAdvert_KEYS.Marshal(b, m, deterministic)
}
func (dst *Ipv4RibEdmAdvert_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ipv4RibEdmAdvert_KEYS.Merge(dst, src)
}
func (m *Ipv4RibEdmAdvert_KEYS) XXX_Size() int {
	return xxx_messageInfo_Ipv4RibEdmAdvert_KEYS.Size(m)
}
func (m *Ipv4RibEdmAdvert_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_Ipv4RibEdmAdvert_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_Ipv4RibEdmAdvert_KEYS proto.InternalMessageInfo

func (m *Ipv4RibEdmAdvert_KEYS) GetVrfName() string {
	if m != nil {
		return m.VrfName
	}
	return ""
}

func (m *Ipv4RibEdmAdvert_KEYS) GetAfName() string {
	if m != nil {
		return m.AfName
	}
	return ""
}

func (m *Ipv4RibEdmAdvert_KEYS) GetSafName() string {
	if m != nil {
		return m.SafName
	}
	return ""
}

func (m *Ipv4RibEdmAdvert_KEYS) GetRouteTableName() string {
	if m != nil {
		return m.RouteTableName
	}
	return ""
}

func (m *Ipv4RibEdmAdvert_KEYS) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Ipv4RibEdmAdvert_KEYS) GetPrefixLength() uint32 {
	if m != nil {
		return m.PrefixLength
	}
	return 0
}

type Ipv4RibEdmAdvert struct {
	// Next advertising proto
	Ipv4RibEdmAdvert     []*Ipv4RibEdmAdvertItem `protobuf:"bytes,50,rep,name=ipv4_rib_edm_advert,json=ipv4RibEdmAdvert,proto3" json:"ipv4_rib_edm_advert,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Ipv4RibEdmAdvert) Reset()         { *m = Ipv4RibEdmAdvert{} }
func (m *Ipv4RibEdmAdvert) String() string { return proto.CompactTextString(m) }
func (*Ipv4RibEdmAdvert) ProtoMessage()    {}
func (*Ipv4RibEdmAdvert) Descriptor() ([]byte, []int) {
	return fileDescriptor_ipv4_rib_edm_advert_0cad3ad845b7d984, []int{1}
}
func (m *Ipv4RibEdmAdvert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ipv4RibEdmAdvert.Unmarshal(m, b)
}
func (m *Ipv4RibEdmAdvert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ipv4RibEdmAdvert.Marshal(b, m, deterministic)
}
func (dst *Ipv4RibEdmAdvert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ipv4RibEdmAdvert.Merge(dst, src)
}
func (m *Ipv4RibEdmAdvert) XXX_Size() int {
	return xxx_messageInfo_Ipv4RibEdmAdvert.Size(m)
}
func (m *Ipv4RibEdmAdvert) XXX_DiscardUnknown() {
	xxx_messageInfo_Ipv4RibEdmAdvert.DiscardUnknown(m)
}

var xxx_messageInfo_Ipv4RibEdmAdvert proto.InternalMessageInfo

func (m *Ipv4RibEdmAdvert) GetIpv4RibEdmAdvert() []*Ipv4RibEdmAdvertItem {
	if m != nil {
		return m.Ipv4RibEdmAdvert
	}
	return nil
}

type Ipv4RibEdmAdvertItem struct {
	// Protocol advertising the route
	ProtocolId uint32 `protobuf:"varint,1,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	//   Client advertising the route
	ClientId uint32 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Number of extended communities
	NumberOfExtendedCommunities uint32 `protobuf:"varint,3,opt,name=number_of_extended_communities,json=numberOfExtendedCommunities,proto3" json:"number_of_extended_communities,omitempty"`
	// Extended communities
	ExtendedCommunities []byte `protobuf:"bytes,4,opt,name=extended_communities,json=extendedCommunities,proto3" json:"extended_communities,omitempty"`
	// OSPF area-id flags
	ProtocolOpaqueFlags uint32 `protobuf:"varint,5,opt,name=protocol_opaque_flags,json=protocolOpaqueFlags,proto3" json:"protocol_opaque_flags,omitempty"`
	// OSPF area-id
	ProtocolOpaque uint32 `protobuf:"varint,6,opt,name=protocol_opaque,json=protocolOpaque,proto3" json:"protocol_opaque,omitempty"`
	// Protocol code
	Code int32 `protobuf:"zigzag32,7,opt,name=code,proto3" json:"code,omitempty"`
	// Instance name
	InstanceName         []byte   `protobuf:"bytes,8,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ipv4RibEdmAdvertItem) Reset()         { *m = Ipv4RibEdmAdvertItem{} }
func (m *Ipv4RibEdmAdvertItem) String() string { return proto.CompactTextString(m) }
func (*Ipv4RibEdmAdvertItem) ProtoMessage()    {}
func (*Ipv4RibEdmAdvertItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ipv4_rib_edm_advert_0cad3ad845b7d984, []int{2}
}
func (m *Ipv4RibEdmAdvertItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ipv4RibEdmAdvertItem.Unmarshal(m, b)
}
func (m *Ipv4RibEdmAdvertItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ipv4RibEdmAdvertItem.Marshal(b, m, deterministic)
}
func (dst *Ipv4RibEdmAdvertItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ipv4RibEdmAdvertItem.Merge(dst, src)
}
func (m *Ipv4RibEdmAdvertItem) XXX_Size() int {
	return xxx_messageInfo_Ipv4RibEdmAdvertItem.Size(m)
}
func (m *Ipv4RibEdmAdvertItem) XXX_DiscardUnknown() {
	xxx_messageInfo_Ipv4RibEdmAdvertItem.DiscardUnknown(m)
}

var xxx_messageInfo_Ipv4RibEdmAdvertItem proto.InternalMessageInfo

func (m *Ipv4RibEdmAdvertItem) GetProtocolId() uint32 {
	if m != nil {
		return m.ProtocolId
	}
	return 0
}

func (m *Ipv4RibEdmAdvertItem) GetClientId() uint32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Ipv4RibEdmAdvertItem) GetNumberOfExtendedCommunities() uint32 {
	if m != nil {
		return m.NumberOfExtendedCommunities
	}
	return 0
}

func (m *Ipv4RibEdmAdvertItem) GetExtendedCommunities() []byte {
	if m != nil {
		return m.ExtendedCommunities
	}
	return nil
}

func (m *Ipv4RibEdmAdvertItem) GetProtocolOpaqueFlags() uint32 {
	if m != nil {
		return m.ProtocolOpaqueFlags
	}
	return 0
}

func (m *Ipv4RibEdmAdvertItem) GetProtocolOpaque() uint32 {
	if m != nil {
		return m.ProtocolOpaque
	}
	return 0
}

func (m *Ipv4RibEdmAdvertItem) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Ipv4RibEdmAdvertItem) GetInstanceName() []byte {
	if m != nil {
		return m.InstanceName
	}
	return nil
}

func init() {
	proto.RegisterType((*Ipv4RibEdmAdvert_KEYS)(nil), "cisco_ios_xr_ip_rib_ipv4_oper.rib.vrfs.vrf.afs.af.safs.saf.ip_rib_route_table_names.ip_rib_route_table_name.adverts.advert.ipv4_rib_edm_advert_KEYS")
	proto.RegisterType((*Ipv4RibEdmAdvert)(nil), "cisco_ios_xr_ip_rib_ipv4_oper.rib.vrfs.vrf.afs.af.safs.saf.ip_rib_route_table_names.ip_rib_route_table_name.adverts.advert.ipv4_rib_edm_advert")
	proto.RegisterType((*Ipv4RibEdmAdvertItem)(nil), "cisco_ios_xr_ip_rib_ipv4_oper.rib.vrfs.vrf.afs.af.safs.saf.ip_rib_route_table_names.ip_rib_route_table_name.adverts.advert.ipv4_rib_edm_advert_item")
}

func init() {
	proto.RegisterFile("ipv4_rib_edm_advert.proto", fileDescriptor_ipv4_rib_edm_advert_0cad3ad845b7d984)
}

var fileDescriptor_ipv4_rib_edm_advert_0cad3ad845b7d984 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0x95, 0x6e, 0xb4, 0x9d, 0xd7, 0x8c, 0xe1, 0x82, 0x48, 0x35, 0x09, 0xaa, 0x71, 0x20,
	0x27, 0x4b, 0x14, 0x5e, 0x00, 0x4d, 0x45, 0x9a, 0x40, 0x4c, 0x32, 0x5c, 0x38, 0x59, 0x4e, 0xfc,
	0xf7, 0xb0, 0x94, 0xc4, 0xc1, 0x76, 0xa3, 0x8a, 0xe7, 0xe0, 0x91, 0x78, 0x02, 0xce, 0x9c, 0x79,
	0x0e, 0x64, 0x3b, 0x01, 0x51, 0x85, 0xf3, 0x2e, 0x75, 0xf3, 0xfd, 0xbe, 0xbf, 0xf3, 0x8f, 0xbe,
	0x0f, 0xad, 0x54, 0xdb, 0xbd, 0x62, 0x46, 0x15, 0x0c, 0x44, 0xcd, 0xb8, 0xe8, 0xc0, 0x38, 0xd2,
	0x1a, 0xed, 0x34, 0xfe, 0x5a, 0x2a, 0x5b, 0x6a, 0xa6, 0xb4, 0x65, 0x7b, 0xc3, 0x54, 0x1b, 0x5c,
	0xc1, 0xae, 0x5b, 0x30, 0xc4, 0xa8, 0x82, 0x74, 0x46, 0x5a, 0xff, 0x43, 0xb8, 0xb4, 0x84, 0x4b,
	0x62, 0xfd, 0x69, 0xb9, 0x24, 0xbd, 0xdb, 0xe8, 0x9d, 0x03, 0xe6, 0x78, 0x51, 0x01, 0x6b, 0x78,
	0x0d, 0xf6, 0x7f, 0x80, 0xc4, 0x37, 0xdb, 0xfe, 0xbc, 0xfc, 0x91, 0xa0, 0x6c, 0x64, 0x33, 0xf6,
	0x76, 0xfb, 0xe9, 0x03, 0x5e, 0xa1, 0x79, 0x67, 0x64, 0x98, 0xcb, 0x92, 0x75, 0x92, 0x9f, 0xd0,
	0x59, 0x67, 0xe4, 0x7b, 0x5e, 0x03, 0x7e, 0x8c, 0x66, 0xbc, 0x27, 0x93, 0x40, 0xa6, 0x3c, 0x82,
	0x15, 0x9a, 0xdb, 0x81, 0x1c, 0xc5, 0x19, 0xdb, 0xa3, 0x1c, 0x9d, 0x1f, 0xae, 0x93, 0x1d, 0x07,
	0xcb, 0x59, 0xd0, 0x3f, 0x7a, 0x39, 0x38, 0x33, 0x34, 0xe3, 0x42, 0x18, 0xb0, 0x36, 0xbb, 0x17,
	0xef, 0xe8, 0x1f, 0xf1, 0x33, 0x94, 0xb6, 0x06, 0xa4, 0xda, 0xb3, 0x0a, 0x9a, 0x5b, 0xf7, 0x39,
	0x9b, 0xae, 0x93, 0x3c, 0xa5, 0x8b, 0x28, 0xbe, 0x0b, 0xda, 0xe5, 0xcf, 0x04, 0x2d, 0x47, 0x3e,
	0x0a, 0x7f, 0x1f, 0xd7, 0xb3, 0xcd, 0xfa, 0x28, 0x3f, 0xdd, 0x7c, 0x4b, 0xc8, 0xdd, 0x05, 0x41,
	0xc6, 0x42, 0x50, 0x0e, 0x6a, 0x7a, 0xee, 0x09, 0x55, 0xc5, 0x56, 0xd4, 0xaf, 0x63, 0x66, 0xbf,
	0x26, 0xe3, 0x99, 0x79, 0x3b, 0x7e, 0x8a, 0x4e, 0x43, 0xab, 0x4a, 0x5d, 0x31, 0x25, 0x42, 0x6c,
	0x29, 0x45, 0x83, 0x74, 0x2d, 0xf0, 0x05, 0x3a, 0x29, 0x2b, 0x05, 0x8d, 0xf3, 0x78, 0x12, 0xf0,
	0x3c, 0x0a, 0xd7, 0x02, 0x5f, 0xa1, 0x27, 0xcd, 0xae, 0x2e, 0xc0, 0x30, 0x2d, 0x19, 0xec, 0x1d,
	0x34, 0x02, 0x04, 0x2b, 0x75, 0x5d, 0xef, 0x1a, 0xe5, 0x14, 0xd8, 0x90, 0x69, 0x4a, 0x2f, 0xa2,
	0xeb, 0x46, 0x6e, 0x7b, 0xcf, 0xd5, 0x5f, 0x0b, 0x7e, 0x81, 0x1e, 0x8e, 0x8e, 0xfa, 0xac, 0x17,
	0x74, 0x09, 0x23, 0x23, 0x1b, 0xf4, 0xe8, 0xcf, 0xd6, 0xba, 0xe5, 0x5f, 0x76, 0xc0, 0x64, 0xc5,
	0x6f, 0x63, 0xfc, 0x29, 0x5d, 0x0e, 0xf0, 0x26, 0xb0, 0x37, 0x1e, 0xe1, 0xe7, 0xe8, 0xfe, 0xc1,
	0x4c, 0x5f, 0x86, 0xb3, 0x7f, 0xdd, 0x18, 0xa3, 0xe3, 0x52, 0x0b, 0xc8, 0x66, 0xeb, 0x24, 0x7f,
	0x40, 0xc3, 0x7f, 0xdf, 0x23, 0xd5, 0x58, 0xc7, 0x9b, 0xb2, 0x2f, 0xe2, 0x3c, 0x2c, 0xb7, 0x18,
	0x44, 0x5f, 0xc3, 0x62, 0x1a, 0x2e, 0x7a, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x3d, 0x37,
	0xb5, 0xbc, 0x03, 0x00, 0x00,
}
