// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im_if_summary_info.proto

package cisco_ios_xr_pfi_im_cmd_oper_interfaces_interface_summary

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Interface summary bag
type ImIfSummaryInfo_KEYS struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImIfSummaryInfo_KEYS) Reset()         { *m = ImIfSummaryInfo_KEYS{} }
func (m *ImIfSummaryInfo_KEYS) String() string { return proto.CompactTextString(m) }
func (*ImIfSummaryInfo_KEYS) ProtoMessage()    {}
func (*ImIfSummaryInfo_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f1e7e171affb549, []int{0}
}

func (m *ImIfSummaryInfo_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImIfSummaryInfo_KEYS.Unmarshal(m, b)
}
func (m *ImIfSummaryInfo_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImIfSummaryInfo_KEYS.Marshal(b, m, deterministic)
}
func (m *ImIfSummaryInfo_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImIfSummaryInfo_KEYS.Merge(m, src)
}
func (m *ImIfSummaryInfo_KEYS) XXX_Size() int {
	return xxx_messageInfo_ImIfSummaryInfo_KEYS.Size(m)
}
func (m *ImIfSummaryInfo_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_ImIfSummaryInfo_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_ImIfSummaryInfo_KEYS proto.InternalMessageInfo

type ImIfSummaryInfo struct {
	// List of per interface type summary information
	InterfaceTypeList []*ImIfTypeSummarySt `protobuf:"bytes,50,rep,name=interface_type_list,json=interfaceTypeList,proto3" json:"interface_type_list,omitempty"`
	// Counts for all interfaces
	InterfaceCounts      *ImIfGroupCountsSt `protobuf:"bytes,51,opt,name=interface_counts,json=interfaceCounts,proto3" json:"interface_counts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ImIfSummaryInfo) Reset()         { *m = ImIfSummaryInfo{} }
func (m *ImIfSummaryInfo) String() string { return proto.CompactTextString(m) }
func (*ImIfSummaryInfo) ProtoMessage()    {}
func (*ImIfSummaryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f1e7e171affb549, []int{1}
}

func (m *ImIfSummaryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImIfSummaryInfo.Unmarshal(m, b)
}
func (m *ImIfSummaryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImIfSummaryInfo.Marshal(b, m, deterministic)
}
func (m *ImIfSummaryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImIfSummaryInfo.Merge(m, src)
}
func (m *ImIfSummaryInfo) XXX_Size() int {
	return xxx_messageInfo_ImIfSummaryInfo.Size(m)
}
func (m *ImIfSummaryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ImIfSummaryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ImIfSummaryInfo proto.InternalMessageInfo

func (m *ImIfSummaryInfo) GetInterfaceTypeList() []*ImIfTypeSummarySt {
	if m != nil {
		return m.InterfaceTypeList
	}
	return nil
}

func (m *ImIfSummaryInfo) GetInterfaceCounts() *ImIfGroupCountsSt {
	if m != nil {
		return m.InterfaceCounts
	}
	return nil
}

type ImIfGroupCountsSt struct {
	// Number of interfaces
	InterfaceCount uint32 `protobuf:"varint,1,opt,name=interface_count,json=interfaceCount,proto3" json:"interface_count,omitempty"`
	// Number of interfaces in UP state
	UpInterfaceCount uint32 `protobuf:"varint,2,opt,name=up_interface_count,json=upInterfaceCount,proto3" json:"up_interface_count,omitempty"`
	// Number of interfaces in DOWN state
	DownInterfaceCount uint32 `protobuf:"varint,3,opt,name=down_interface_count,json=downInterfaceCount,proto3" json:"down_interface_count,omitempty"`
	// Number of interfaces in an ADMINDOWN state
	AdminDownInterfaceCount uint32   `protobuf:"varint,4,opt,name=admin_down_interface_count,json=adminDownInterfaceCount,proto3" json:"admin_down_interface_count,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ImIfGroupCountsSt) Reset()         { *m = ImIfGroupCountsSt{} }
func (m *ImIfGroupCountsSt) String() string { return proto.CompactTextString(m) }
func (*ImIfGroupCountsSt) ProtoMessage()    {}
func (*ImIfGroupCountsSt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f1e7e171affb549, []int{2}
}

func (m *ImIfGroupCountsSt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImIfGroupCountsSt.Unmarshal(m, b)
}
func (m *ImIfGroupCountsSt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImIfGroupCountsSt.Marshal(b, m, deterministic)
}
func (m *ImIfGroupCountsSt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImIfGroupCountsSt.Merge(m, src)
}
func (m *ImIfGroupCountsSt) XXX_Size() int {
	return xxx_messageInfo_ImIfGroupCountsSt.Size(m)
}
func (m *ImIfGroupCountsSt) XXX_DiscardUnknown() {
	xxx_messageInfo_ImIfGroupCountsSt.DiscardUnknown(m)
}

var xxx_messageInfo_ImIfGroupCountsSt proto.InternalMessageInfo

func (m *ImIfGroupCountsSt) GetInterfaceCount() uint32 {
	if m != nil {
		return m.InterfaceCount
	}
	return 0
}

func (m *ImIfGroupCountsSt) GetUpInterfaceCount() uint32 {
	if m != nil {
		return m.UpInterfaceCount
	}
	return 0
}

func (m *ImIfGroupCountsSt) GetDownInterfaceCount() uint32 {
	if m != nil {
		return m.DownInterfaceCount
	}
	return 0
}

func (m *ImIfGroupCountsSt) GetAdminDownInterfaceCount() uint32 {
	if m != nil {
		return m.AdminDownInterfaceCount
	}
	return 0
}

type ImIfTypeSummarySt struct {
	// Name of the interface type
	InterfaceTypeName string `protobuf:"bytes,1,opt,name=interface_type_name,json=interfaceTypeName,proto3" json:"interface_type_name,omitempty"`
	// Description of the interface type
	InterfaceTypeDescription string `protobuf:"bytes,2,opt,name=interface_type_description,json=interfaceTypeDescription,proto3" json:"interface_type_description,omitempty"`
	// Counts for interfaces of this type
	InterfaceCounts      *ImIfGroupCountsSt `protobuf:"bytes,3,opt,name=interface_counts,json=interfaceCounts,proto3" json:"interface_counts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ImIfTypeSummarySt) Reset()         { *m = ImIfTypeSummarySt{} }
func (m *ImIfTypeSummarySt) String() string { return proto.CompactTextString(m) }
func (*ImIfTypeSummarySt) ProtoMessage()    {}
func (*ImIfTypeSummarySt) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f1e7e171affb549, []int{3}
}

func (m *ImIfTypeSummarySt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImIfTypeSummarySt.Unmarshal(m, b)
}
func (m *ImIfTypeSummarySt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImIfTypeSummarySt.Marshal(b, m, deterministic)
}
func (m *ImIfTypeSummarySt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImIfTypeSummarySt.Merge(m, src)
}
func (m *ImIfTypeSummarySt) XXX_Size() int {
	return xxx_messageInfo_ImIfTypeSummarySt.Size(m)
}
func (m *ImIfTypeSummarySt) XXX_DiscardUnknown() {
	xxx_messageInfo_ImIfTypeSummarySt.DiscardUnknown(m)
}

var xxx_messageInfo_ImIfTypeSummarySt proto.InternalMessageInfo

func (m *ImIfTypeSummarySt) GetInterfaceTypeName() string {
	if m != nil {
		return m.InterfaceTypeName
	}
	return ""
}

func (m *ImIfTypeSummarySt) GetInterfaceTypeDescription() string {
	if m != nil {
		return m.InterfaceTypeDescription
	}
	return ""
}

func (m *ImIfTypeSummarySt) GetInterfaceCounts() *ImIfGroupCountsSt {
	if m != nil {
		return m.InterfaceCounts
	}
	return nil
}

func init() {
	proto.RegisterType((*ImIfSummaryInfo_KEYS)(nil), "cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_summary_info_KEYS")
	proto.RegisterType((*ImIfSummaryInfo)(nil), "cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_summary_info")
	proto.RegisterType((*ImIfGroupCountsSt)(nil), "cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_group_counts_st")
	proto.RegisterType((*ImIfTypeSummarySt)(nil), "cisco_ios_xr_pfi_im_cmd_oper.interfaces.interface_summary.im_if_type_summary_st")
}

func init() { proto.RegisterFile("im_if_summary_info.proto", fileDescriptor_1f1e7e171affb549) }

var fileDescriptor_1f1e7e171affb549 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x49, 0x2b, 0x42, 0x57, 0xb4, 0x75, 0x55, 0x1a, 0x7b, 0x2a, 0xb9, 0xd8, 0x83, 0x04,
	0x69, 0x4f, 0xa2, 0x37, 0xeb, 0x41, 0x14, 0x91, 0xea, 0xc5, 0xd3, 0x10, 0x37, 0x1b, 0x19, 0x70,
	0xff, 0xb0, 0xbb, 0x41, 0x8b, 0x17, 0xf1, 0x33, 0xf8, 0xf5, 0xfc, 0x2e, 0xd2, 0xd5, 0x36, 0x74,
	0xd3, 0x93, 0x88, 0xb7, 0x90, 0xf9, 0xbd, 0xf7, 0x66, 0x78, 0x2c, 0x89, 0x51, 0x00, 0x16, 0x60,
	0x4b, 0x21, 0x32, 0x33, 0x05, 0x94, 0x85, 0x4a, 0xb5, 0x51, 0x4e, 0xd1, 0x63, 0x86, 0x96, 0x29,
	0x40, 0x65, 0xe1, 0xc5, 0x80, 0x2e, 0x10, 0x50, 0x00, 0x13, 0x39, 0x28, 0xcd, 0x4d, 0x8a, 0xd2,
	0x71, 0x53, 0x64, 0x8c, 0xdb, 0xea, 0x73, 0xee, 0x92, 0xec, 0x93, 0x6e, 0xdd, 0x16, 0x2e, 0xcf,
	0xef, 0x6f, 0x93, 0x8f, 0x06, 0xa1, 0xf5, 0x19, 0x7d, 0x8b, 0xc8, 0x4e, 0xe5, 0xe3, 0xa6, 0x9a,
	0xc3, 0x13, 0x5a, 0x17, 0x0f, 0xfb, 0xcd, 0xc1, 0xc6, 0xf0, 0x26, 0xfd, 0xf5, 0x2e, 0xe9, 0x77,
	0x98, 0x77, 0x9c, 0x27, 0x5a, 0x37, 0xd9, 0x5e, 0x80, 0x77, 0x53, 0xcd, 0xaf, 0xd0, 0x3a, 0xfa,
	0x4a, 0x3a, 0x95, 0x9a, 0xa9, 0x52, 0x3a, 0x1b, 0x8f, 0xfa, 0xd1, 0x9f, 0xc4, 0x3f, 0x1a, 0x55,
	0xea, 0x1f, 0xd3, 0x59, 0x7c, 0x7b, 0x01, 0x9e, 0xf9, 0x7f, 0xc9, 0x67, 0x44, 0xf6, 0x56, 0xa2,
	0xf4, 0x80, 0xb4, 0x83, 0xb5, 0xe2, 0xa8, 0x1f, 0x0d, 0x36, 0x27, 0x5b, 0xcb, 0x1e, 0xf4, 0x90,
	0xd0, 0x52, 0x43, 0xc8, 0x36, 0x3c, 0xdb, 0x29, 0xf5, 0xc5, 0x32, 0x7d, 0x44, 0x76, 0x73, 0xf5,
	0x2c, 0x6b, 0x7c, 0xd3, 0xf3, 0x74, 0x36, 0x0b, 0x14, 0x27, 0xa4, 0x97, 0xe5, 0x02, 0x25, 0xac,
	0xd4, 0xad, 0x79, 0x5d, 0xd7, 0x13, 0xe3, 0x9a, 0x38, 0x79, 0x6f, 0xcc, 0xef, 0x0b, 0x9a, 0xa0,
	0x69, 0xad, 0x78, 0x99, 0x09, 0xee, 0x6f, 0x6c, 0x05, 0x35, 0x5d, 0x67, 0x82, 0xd3, 0x53, 0xd2,
	0x0b, 0xf8, 0x9c, 0x5b, 0x66, 0x50, 0x3b, 0x54, 0xd2, 0x9f, 0xdb, 0x9a, 0xc4, 0x4b, 0xb2, 0x71,
	0x35, 0x5f, 0x59, 0x72, 0xf3, 0x9f, 0x4a, 0x7e, 0x58, 0xf7, 0x0f, 0x6b, 0xf4, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x92, 0x1b, 0x34, 0x17, 0x74, 0x03, 0x00, 0x00,
}
