// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vrrp_trackitem_info.proto

package cisco_ios_xr_ipv4_vrrp_oper_vrrp_ipv4_track_items_track_item

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Tracked item information
type VrrpTrackitemInfo_KEYS struct {
	InterfaceName        string   `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	VirtualRouterId      uint32   `protobuf:"varint,2,opt,name=virtual_router_id,json=virtualRouterId,proto3" json:"virtual_router_id,omitempty"`
	TrackedInterfaceName string   `protobuf:"bytes,3,opt,name=tracked_interface_name,json=trackedInterfaceName,proto3" json:"tracked_interface_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VrrpTrackitemInfo_KEYS) Reset()         { *m = VrrpTrackitemInfo_KEYS{} }
func (m *VrrpTrackitemInfo_KEYS) String() string { return proto.CompactTextString(m) }
func (*VrrpTrackitemInfo_KEYS) ProtoMessage()    {}
func (*VrrpTrackitemInfo_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_75247e93c2102220, []int{0}
}

func (m *VrrpTrackitemInfo_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VrrpTrackitemInfo_KEYS.Unmarshal(m, b)
}
func (m *VrrpTrackitemInfo_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VrrpTrackitemInfo_KEYS.Marshal(b, m, deterministic)
}
func (m *VrrpTrackitemInfo_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VrrpTrackitemInfo_KEYS.Merge(m, src)
}
func (m *VrrpTrackitemInfo_KEYS) XXX_Size() int {
	return xxx_messageInfo_VrrpTrackitemInfo_KEYS.Size(m)
}
func (m *VrrpTrackitemInfo_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_VrrpTrackitemInfo_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_VrrpTrackitemInfo_KEYS proto.InternalMessageInfo

func (m *VrrpTrackitemInfo_KEYS) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *VrrpTrackitemInfo_KEYS) GetVirtualRouterId() uint32 {
	if m != nil {
		return m.VirtualRouterId
	}
	return 0
}

func (m *VrrpTrackitemInfo_KEYS) GetTrackedInterfaceName() string {
	if m != nil {
		return m.TrackedInterfaceName
	}
	return ""
}

type VrrpTrackitemInfo struct {
	// IM Interface
	Interface string `protobuf:"bytes,50,opt,name=interface,proto3" json:"interface,omitempty"`
	// Virtual Router ID
	VirtualRouterId uint32 `protobuf:"varint,51,opt,name=virtual_router_id,json=virtualRouterId,proto3" json:"virtual_router_id,omitempty"`
	// Type of tracked item
	TrackedItemType uint32 `protobuf:"varint,52,opt,name=tracked_item_type,json=trackedItemType,proto3" json:"tracked_item_type,omitempty"`
	// Tracked item index
	TrackedItemIndex string `protobuf:"bytes,53,opt,name=tracked_item_index,json=trackedItemIndex,proto3" json:"tracked_item_index,omitempty"`
	// State of the tracked item
	State uint32 `protobuf:"varint,54,opt,name=state,proto3" json:"state,omitempty"`
	// Priority weight of item
	Priority             uint32   `protobuf:"varint,55,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VrrpTrackitemInfo) Reset()         { *m = VrrpTrackitemInfo{} }
func (m *VrrpTrackitemInfo) String() string { return proto.CompactTextString(m) }
func (*VrrpTrackitemInfo) ProtoMessage()    {}
func (*VrrpTrackitemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_75247e93c2102220, []int{1}
}

func (m *VrrpTrackitemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VrrpTrackitemInfo.Unmarshal(m, b)
}
func (m *VrrpTrackitemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VrrpTrackitemInfo.Marshal(b, m, deterministic)
}
func (m *VrrpTrackitemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VrrpTrackitemInfo.Merge(m, src)
}
func (m *VrrpTrackitemInfo) XXX_Size() int {
	return xxx_messageInfo_VrrpTrackitemInfo.Size(m)
}
func (m *VrrpTrackitemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VrrpTrackitemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VrrpTrackitemInfo proto.InternalMessageInfo

func (m *VrrpTrackitemInfo) GetInterface() string {
	if m != nil {
		return m.Interface
	}
	return ""
}

func (m *VrrpTrackitemInfo) GetVirtualRouterId() uint32 {
	if m != nil {
		return m.VirtualRouterId
	}
	return 0
}

func (m *VrrpTrackitemInfo) GetTrackedItemType() uint32 {
	if m != nil {
		return m.TrackedItemType
	}
	return 0
}

func (m *VrrpTrackitemInfo) GetTrackedItemIndex() string {
	if m != nil {
		return m.TrackedItemIndex
	}
	return ""
}

func (m *VrrpTrackitemInfo) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *VrrpTrackitemInfo) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func init() {
	proto.RegisterType((*VrrpTrackitemInfo_KEYS)(nil), "cisco_ios_xr_ipv4_vrrp_oper.vrrp.ipv4.track_items.track_item.vrrp_trackitem_info_KEYS")
	proto.RegisterType((*VrrpTrackitemInfo)(nil), "cisco_ios_xr_ipv4_vrrp_oper.vrrp.ipv4.track_items.track_item.vrrp_trackitem_info")
}

func init() { proto.RegisterFile("vrrp_trackitem_info.proto", fileDescriptor_75247e93c2102220) }

var fileDescriptor_75247e93c2102220 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0xa2, 0xd8, 0x85, 0xaa, 0x5d, 0x8b, 0xac, 0xe2, 0xa1, 0x14, 0x84, 0x52, 0x24,
	0x07, 0x1b, 0xf5, 0xe2, 0xd5, 0x43, 0x10, 0x3c, 0x44, 0x2f, 0x9e, 0x86, 0x35, 0x99, 0xc2, 0xa2,
	0xc9, 0x2e, 0x93, 0x69, 0x68, 0x7e, 0x8f, 0x3f, 0xcf, 0x3f, 0x21, 0xd9, 0xd6, 0x18, 0x25, 0xb7,
	0x9d, 0x37, 0x6f, 0xbe, 0xf7, 0x60, 0xc5, 0x59, 0x45, 0xe4, 0x80, 0x49, 0xa7, 0xef, 0x86, 0x31,
	0x07, 0x53, 0x2c, 0x6d, 0xe8, 0xc8, 0xb2, 0x95, 0xf7, 0xa9, 0x29, 0x53, 0x0b, 0xc6, 0x96, 0xb0,
	0x26, 0x30, 0xae, 0x8a, 0xc0, 0x9b, 0xad, 0x43, 0x0a, 0x9b, 0x57, 0xd8, 0x68, 0xa1, 0xbf, 0x85,
	0xe6, 0xb8, 0xec, 0xbc, 0xa7, 0x9f, 0x81, 0x50, 0x3d, 0x6c, 0x78, 0x7c, 0x78, 0x7d, 0x96, 0x97,
	0xe2, 0xd0, 0x14, 0x8c, 0xb4, 0xd4, 0x29, 0x42, 0xa1, 0x73, 0x54, 0xc1, 0x24, 0x98, 0x0d, 0x92,
	0x61, 0xab, 0x3e, 0xe9, 0x1c, 0xe5, 0x5c, 0x8c, 0x2a, 0x43, 0xbc, 0xd2, 0x1f, 0x40, 0x76, 0xc5,
	0x48, 0x60, 0x32, 0xb5, 0x33, 0x09, 0x66, 0xc3, 0xe4, 0x68, 0xbb, 0x48, 0xbc, 0x1e, 0x67, 0x32,
	0x12, 0xa7, 0x3e, 0x09, 0x33, 0xf8, 0x87, 0xde, 0xf5, 0xe8, 0xf1, 0x76, 0x1b, 0x77, 0x13, 0xa6,
	0x5f, 0x81, 0x38, 0xe9, 0x69, 0x29, 0x2f, 0xc4, 0xa0, 0xa5, 0xa8, 0x6b, 0x0f, 0xf8, 0x15, 0xfa,
	0x7b, 0x2d, 0xfa, 0x7b, 0xcd, 0xc5, 0xa8, 0xed, 0xd5, 0xe0, 0xb9, 0x76, 0xa8, 0xa2, 0x8d, 0xf7,
	0xa7, 0x12, 0x63, 0xfe, 0x52, 0x3b, 0x94, 0x57, 0x42, 0xfe, 0xf1, 0x9a, 0x22, 0xc3, 0xb5, 0xba,
	0xf1, 0xf1, 0xc7, 0x1d, 0x73, 0xdc, 0xe8, 0x72, 0x2c, 0xf6, 0x4a, 0xd6, 0x8c, 0xea, 0xd6, 0xd3,
	0x36, 0x83, 0x3c, 0x17, 0x07, 0x8e, 0x8c, 0x25, 0xc3, 0xb5, 0xba, 0xf3, 0x8b, 0x76, 0x7e, 0xdb,
	0xf7, 0x1f, 0xbb, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x6a, 0xdb, 0x3f, 0xf5, 0x01, 0x00,
	0x00,
}
