// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lldp_interface.proto

package cisco_ios_xr_ethernet_lldp_oper_lldp_nodes_node_interfaces_interface

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Information about an interface that LLDP is running on
type LldpInterface_KEYS struct {
	NodeName             string   `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	InterfaceName        string   `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LldpInterface_KEYS) Reset()         { *m = LldpInterface_KEYS{} }
func (m *LldpInterface_KEYS) String() string { return proto.CompactTextString(m) }
func (*LldpInterface_KEYS) ProtoMessage()    {}
func (*LldpInterface_KEYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b3ff674eb4959e2, []int{0}
}

func (m *LldpInterface_KEYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpInterface_KEYS.Unmarshal(m, b)
}
func (m *LldpInterface_KEYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpInterface_KEYS.Marshal(b, m, deterministic)
}
func (m *LldpInterface_KEYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpInterface_KEYS.Merge(m, src)
}
func (m *LldpInterface_KEYS) XXX_Size() int {
	return xxx_messageInfo_LldpInterface_KEYS.Size(m)
}
func (m *LldpInterface_KEYS) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpInterface_KEYS.DiscardUnknown(m)
}

var xxx_messageInfo_LldpInterface_KEYS proto.InternalMessageInfo

func (m *LldpInterface_KEYS) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *LldpInterface_KEYS) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

type LldpInterface struct {
	// Interface
	InterfaceName string `protobuf:"bytes,50,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// TX Enabled
	TxEnabled uint32 `protobuf:"varint,51,opt,name=tx_enabled,json=txEnabled,proto3" json:"tx_enabled,omitempty"`
	// RX Enabled
	RxEnabled uint32 `protobuf:"varint,52,opt,name=rx_enabled,json=rxEnabled,proto3" json:"rx_enabled,omitempty"`
	// TX State
	TxState string `protobuf:"bytes,53,opt,name=tx_state,json=txState,proto3" json:"tx_state,omitempty"`
	// RX State
	RxState string `protobuf:"bytes,54,opt,name=rx_state,json=rxState,proto3" json:"rx_state,omitempty"`
	// ifIndex
	IfIndex uint32 `protobuf:"varint,55,opt,name=if_index,json=ifIndex,proto3" json:"if_index,omitempty"`
	// Outgoing port identifier
	PortId string `protobuf:"bytes,56,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// Port ID sub type
	PortIdSubType uint32 `protobuf:"varint,57,opt,name=port_id_sub_type,json=portIdSubType,proto3" json:"port_id_sub_type,omitempty"`
	// Port Description
	PortDescription string `protobuf:"bytes,58,opt,name=port_description,json=portDescription,proto3" json:"port_description,omitempty"`
	// Local Management Addresses
	LocalNetworkAddresses *LldpAddrEntry `protobuf:"bytes,59,opt,name=local_network_addresses,json=localNetworkAddresses,proto3" json:"local_network_addresses,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}       `json:"-"`
	XXX_unrecognized      []byte         `json:"-"`
	XXX_sizecache         int32          `json:"-"`
}

func (m *LldpInterface) Reset()         { *m = LldpInterface{} }
func (m *LldpInterface) String() string { return proto.CompactTextString(m) }
func (*LldpInterface) ProtoMessage()    {}
func (*LldpInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b3ff674eb4959e2, []int{1}
}

func (m *LldpInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpInterface.Unmarshal(m, b)
}
func (m *LldpInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpInterface.Marshal(b, m, deterministic)
}
func (m *LldpInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpInterface.Merge(m, src)
}
func (m *LldpInterface) XXX_Size() int {
	return xxx_messageInfo_LldpInterface.Size(m)
}
func (m *LldpInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpInterface.DiscardUnknown(m)
}

var xxx_messageInfo_LldpInterface proto.InternalMessageInfo

func (m *LldpInterface) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *LldpInterface) GetTxEnabled() uint32 {
	if m != nil {
		return m.TxEnabled
	}
	return 0
}

func (m *LldpInterface) GetRxEnabled() uint32 {
	if m != nil {
		return m.RxEnabled
	}
	return 0
}

func (m *LldpInterface) GetTxState() string {
	if m != nil {
		return m.TxState
	}
	return ""
}

func (m *LldpInterface) GetRxState() string {
	if m != nil {
		return m.RxState
	}
	return ""
}

func (m *LldpInterface) GetIfIndex() uint32 {
	if m != nil {
		return m.IfIndex
	}
	return 0
}

func (m *LldpInterface) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *LldpInterface) GetPortIdSubType() uint32 {
	if m != nil {
		return m.PortIdSubType
	}
	return 0
}

func (m *LldpInterface) GetPortDescription() string {
	if m != nil {
		return m.PortDescription
	}
	return ""
}

func (m *LldpInterface) GetLocalNetworkAddresses() *LldpAddrEntry {
	if m != nil {
		return m.LocalNetworkAddresses
	}
	return nil
}

type In6AddrTd struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In6AddrTd) Reset()         { *m = In6AddrTd{} }
func (m *In6AddrTd) String() string { return proto.CompactTextString(m) }
func (*In6AddrTd) ProtoMessage()    {}
func (*In6AddrTd) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b3ff674eb4959e2, []int{2}
}

func (m *In6AddrTd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In6AddrTd.Unmarshal(m, b)
}
func (m *In6AddrTd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In6AddrTd.Marshal(b, m, deterministic)
}
func (m *In6AddrTd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In6AddrTd.Merge(m, src)
}
func (m *In6AddrTd) XXX_Size() int {
	return xxx_messageInfo_In6AddrTd.Size(m)
}
func (m *In6AddrTd) XXX_DiscardUnknown() {
	xxx_messageInfo_In6AddrTd.DiscardUnknown(m)
}

var xxx_messageInfo_In6AddrTd proto.InternalMessageInfo

func (m *In6AddrTd) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type LldpL3Addr struct {
	AddressType string `protobuf:"bytes,1,opt,name=address_type,json=addressType,proto3" json:"address_type,omitempty"`
	// IPv4 address
	Ipv4Address string `protobuf:"bytes,2,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	// IPv6 address
	Ipv6Address          *In6AddrTd `protobuf:"bytes,3,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LldpL3Addr) Reset()         { *m = LldpL3Addr{} }
func (m *LldpL3Addr) String() string { return proto.CompactTextString(m) }
func (*LldpL3Addr) ProtoMessage()    {}
func (*LldpL3Addr) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b3ff674eb4959e2, []int{3}
}

func (m *LldpL3Addr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpL3Addr.Unmarshal(m, b)
}
func (m *LldpL3Addr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpL3Addr.Marshal(b, m, deterministic)
}
func (m *LldpL3Addr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpL3Addr.Merge(m, src)
}
func (m *LldpL3Addr) XXX_Size() int {
	return xxx_messageInfo_LldpL3Addr.Size(m)
}
func (m *LldpL3Addr) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpL3Addr.DiscardUnknown(m)
}

var xxx_messageInfo_LldpL3Addr proto.InternalMessageInfo

func (m *LldpL3Addr) GetAddressType() string {
	if m != nil {
		return m.AddressType
	}
	return ""
}

func (m *LldpL3Addr) GetIpv4Address() string {
	if m != nil {
		return m.Ipv4Address
	}
	return ""
}

func (m *LldpL3Addr) GetIpv6Address() *In6AddrTd {
	if m != nil {
		return m.Ipv6Address
	}
	return nil
}

type LldpAddrEntry struct {
	// Next address entry in list
	LldpAddrEntry        []*LldpAddrEntryItem `protobuf:"bytes,1,rep,name=lldp_addr_entry,json=lldpAddrEntry,proto3" json:"lldp_addr_entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LldpAddrEntry) Reset()         { *m = LldpAddrEntry{} }
func (m *LldpAddrEntry) String() string { return proto.CompactTextString(m) }
func (*LldpAddrEntry) ProtoMessage()    {}
func (*LldpAddrEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b3ff674eb4959e2, []int{4}
}

func (m *LldpAddrEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpAddrEntry.Unmarshal(m, b)
}
func (m *LldpAddrEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpAddrEntry.Marshal(b, m, deterministic)
}
func (m *LldpAddrEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpAddrEntry.Merge(m, src)
}
func (m *LldpAddrEntry) XXX_Size() int {
	return xxx_messageInfo_LldpAddrEntry.Size(m)
}
func (m *LldpAddrEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpAddrEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LldpAddrEntry proto.InternalMessageInfo

func (m *LldpAddrEntry) GetLldpAddrEntry() []*LldpAddrEntryItem {
	if m != nil {
		return m.LldpAddrEntry
	}
	return nil
}

type LldpAddrEntryItem struct {
	// Network layer address
	Address *LldpL3Addr `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// MA sub type
	MaSubtype uint32 `protobuf:"varint,2,opt,name=ma_subtype,json=maSubtype,proto3" json:"ma_subtype,omitempty"`
	// Interface num
	IfNum                uint32   `protobuf:"varint,3,opt,name=if_num,json=ifNum,proto3" json:"if_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LldpAddrEntryItem) Reset()         { *m = LldpAddrEntryItem{} }
func (m *LldpAddrEntryItem) String() string { return proto.CompactTextString(m) }
func (*LldpAddrEntryItem) ProtoMessage()    {}
func (*LldpAddrEntryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b3ff674eb4959e2, []int{5}
}

func (m *LldpAddrEntryItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LldpAddrEntryItem.Unmarshal(m, b)
}
func (m *LldpAddrEntryItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LldpAddrEntryItem.Marshal(b, m, deterministic)
}
func (m *LldpAddrEntryItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LldpAddrEntryItem.Merge(m, src)
}
func (m *LldpAddrEntryItem) XXX_Size() int {
	return xxx_messageInfo_LldpAddrEntryItem.Size(m)
}
func (m *LldpAddrEntryItem) XXX_DiscardUnknown() {
	xxx_messageInfo_LldpAddrEntryItem.DiscardUnknown(m)
}

var xxx_messageInfo_LldpAddrEntryItem proto.InternalMessageInfo

func (m *LldpAddrEntryItem) GetAddress() *LldpL3Addr {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *LldpAddrEntryItem) GetMaSubtype() uint32 {
	if m != nil {
		return m.MaSubtype
	}
	return 0
}

func (m *LldpAddrEntryItem) GetIfNum() uint32 {
	if m != nil {
		return m.IfNum
	}
	return 0
}

func init() {
	proto.RegisterType((*LldpInterface_KEYS)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.interfaces.interface.lldp_interface_KEYS")
	proto.RegisterType((*LldpInterface)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.interfaces.interface.lldp_interface")
	proto.RegisterType((*In6AddrTd)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.interfaces.interface.in6_addr_td")
	proto.RegisterType((*LldpL3Addr)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.interfaces.interface.lldp_l3_addr")
	proto.RegisterType((*LldpAddrEntry)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.interfaces.interface.lldp_addr_entry")
	proto.RegisterType((*LldpAddrEntryItem)(nil), "cisco_ios_xr_ethernet_lldp_oper.lldp.nodes.node.interfaces.interface.lldp_addr_entry_item")
}

func init() { proto.RegisterFile("lldp_interface.proto", fileDescriptor_1b3ff674eb4959e2) }

var fileDescriptor_1b3ff674eb4959e2 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x1b, 0x35, 0x69, 0x36, 0x49, 0x8b, 0x96, 0x56, 0x35, 0x42, 0x48, 0xa9, 0x11, 0x22,
	0x5c, 0x72, 0x48, 0x4a, 0xf8, 0x3a, 0x21, 0x35, 0x87, 0x0a, 0x29, 0x12, 0x0e, 0x1c, 0xca, 0x65,
	0xe5, 0x64, 0x27, 0x62, 0x85, 0xbd, 0x6b, 0xed, 0x6e, 0x8a, 0x73, 0xe5, 0xce, 0x95, 0x1f, 0xc3,
	0x95, 0x1b, 0xbf, 0x0a, 0xed, 0xac, 0x1d, 0xd3, 0xd2, 0x63, 0xb8, 0x58, 0x9e, 0xf7, 0xde, 0xbc,
	0xd9, 0x99, 0x59, 0x9b, 0x1c, 0xa7, 0x29, 0xcf, 0x99, 0x90, 0x16, 0xf4, 0x2a, 0x59, 0xc2, 0x30,
	0xd7, 0xca, 0x2a, 0x7a, 0xb1, 0x14, 0x66, 0xa9, 0x98, 0x50, 0x86, 0x15, 0x9a, 0x81, 0xfd, 0x0c,
	0x5a, 0x82, 0x65, 0xa8, 0x55, 0x39, 0xe8, 0xa1, 0x7b, 0x1b, 0x4a, 0xc5, 0xc1, 0xe0, 0x73, 0xb8,
	0x35, 0x30, 0xf5, 0x6b, 0x74, 0x45, 0xee, 0xdf, 0x74, 0x67, 0xef, 0xa6, 0x57, 0x73, 0xfa, 0x90,
	0xb4, 0x5d, 0x0e, 0x93, 0x49, 0x06, 0x61, 0xd0, 0x0f, 0x06, 0xed, 0xf8, 0xc0, 0x01, 0xb3, 0x24,
	0x03, 0xfa, 0x84, 0x1c, 0xd6, 0x72, 0x54, 0xec, 0xa1, 0xa2, 0xb7, 0x45, 0x9d, 0x2c, 0xfa, 0xd5,
	0x20, 0x87, 0x37, 0xbd, 0xef, 0xc8, 0x1c, 0xdd, 0x91, 0x49, 0x1f, 0x11, 0x62, 0x0b, 0x06, 0x32,
	0x59, 0xa4, 0xc0, 0xc3, 0x71, 0x3f, 0x18, 0xf4, 0xe2, 0xb6, 0x2d, 0xa6, 0x1e, 0x70, 0xb4, 0xae,
	0xe9, 0x73, 0x4f, 0xeb, 0x2d, 0xfd, 0x80, 0x1c, 0xd8, 0x82, 0x19, 0x9b, 0x58, 0x08, 0x9f, 0xa3,
	0x7d, 0xcb, 0x16, 0x73, 0x17, 0x3a, 0x4a, 0x57, 0xd4, 0xc4, 0x53, 0xba, 0xa6, 0xc4, 0x8a, 0x09,
	0xc9, 0xa1, 0x08, 0x5f, 0xa0, 0x65, 0x4b, 0xac, 0x2e, 0x5d, 0x48, 0x4f, 0x49, 0x2b, 0x57, 0xda,
	0x32, 0xc1, 0xc3, 0x97, 0x98, 0xd4, 0x74, 0xe1, 0x25, 0xa7, 0x4f, 0xc9, 0xbd, 0x92, 0x60, 0x66,
	0xbd, 0x60, 0x76, 0x93, 0x43, 0xf8, 0x0a, 0x73, 0x7b, 0x5e, 0x31, 0x5f, 0x2f, 0x3e, 0x6c, 0x72,
	0xa0, 0xcf, 0x4a, 0x21, 0x07, 0xb3, 0xd4, 0x22, 0xb7, 0x42, 0xc9, 0xf0, 0x35, 0x5a, 0x1d, 0x39,
	0xfc, 0xa2, 0x86, 0xe9, 0xf7, 0x80, 0x9c, 0xa6, 0x6a, 0x99, 0xa4, 0x4c, 0x82, 0xfd, 0xaa, 0xf4,
	0x17, 0x96, 0x70, 0xae, 0xc1, 0x18, 0x30, 0xe1, 0x9b, 0x7e, 0x30, 0xe8, 0x8c, 0x3e, 0x0e, 0x77,
	0xb1, 0x79, 0x14, 0xa1, 0x37, 0x03, 0x69, 0xf5, 0x26, 0x3e, 0xc1, 0xaa, 0x33, 0x5f, 0xf4, 0x6d,
	0x55, 0x33, 0x7a, 0x4c, 0x3a, 0x42, 0x4e, 0xbc, 0xd0, 0x72, 0x7a, 0x4c, 0xf6, 0xaf, 0x93, 0x74,
	0x5d, 0x5d, 0x0a, 0x1f, 0x44, 0xbf, 0x03, 0xd2, 0x45, 0xbf, 0x74, 0x8c, 0x4a, 0x7a, 0x46, 0xba,
	0xe5, 0xb1, 0xfd, 0x54, 0xbc, 0xba, 0x53, 0x62, 0x38, 0x93, 0x33, 0xd2, 0x15, 0xf9, 0xf5, 0x79,
	0xd5, 0x5e, 0x79, 0x87, 0x3a, 0x0e, 0x2b, 0xab, 0x53, 0x8b, 0x92, 0xc9, 0x56, 0xd2, 0xc0, 0xfe,
	0xdf, 0xef, 0xa6, 0xff, 0xbf, 0xba, 0xc2, 0xaa, 0x93, 0xb2, 0x6a, 0xf4, 0x23, 0x20, 0x47, 0xb7,
	0x86, 0x43, 0xbf, 0xfd, 0x8b, 0x85, 0x41, 0xbf, 0x31, 0xe8, 0x8c, 0x3e, 0xfd, 0x97, 0x6d, 0x30,
	0x61, 0x21, 0x8b, 0x7b, 0x0e, 0x75, 0xc7, 0x9a, 0x3a, 0x2c, 0xfa, 0x19, 0x94, 0xbf, 0x82, 0x5b,
	0x3a, 0x9a, 0x92, 0x56, 0x35, 0xa2, 0x00, 0x47, 0x14, 0xef, 0xf0, 0x50, 0xe5, 0x4a, 0xe3, 0xaa,
	0x84, 0xfb, 0xfc, 0xb2, 0xc4, 0x5d, 0x78, 0xdc, 0xec, 0x9e, 0xff, 0xfc, 0xb2, 0x64, 0xee, 0x01,
	0x7a, 0x42, 0x9a, 0x62, 0xc5, 0xe4, 0x3a, 0xc3, 0x75, 0xf5, 0xe2, 0x7d, 0xb1, 0x9a, 0xad, 0xb3,
	0x45, 0x13, 0xff, 0x5a, 0xe3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xb2, 0x48, 0xf4, 0xcd,
	0x04, 0x00, 0x00,
}
